import { colors } from '@/utils/constants'

export const Theme = {
  background: colors.sky.c600,
  radius: '0.25rem',
  bg: {
    sky: colors.sky.c700,
    blue: colors.blue.c700,
    indigo: colors.indigo.c700,
    red: colors.red.c700,
    pink: colors.pink.c700,
    orange: colors.orange.c500,
    yellow: colors.yellow.c500,
    lime: colors.lime.c700,
    green: colors.green.c700,
    gray: colors.gray.c500,
  },
  btn: {
    sky: colors.sky.c600,
    blue: colors.blue.c600,
    indigo: colors.indigo.c600,
    red: colors.red.c600,
    pink: colors.pink.c600,
    orange: colors.orange.c400,
    yellow: colors.yellow.c400,
    lime: colors.lime.c600,
    green: colors.green.c600,
    gray: colors.gray.c400,
  },
  focus: {
    sky: colors.sky.c600,
    blue: colors.blue.c600,
    indigo: colors.indigo.c600,
    red: colors.red.c600,
    pink: colors.pink.c600,
    orange: colors.orange.c400,
    yellow: colors.yellow.c400,
    lime: colors.lime.c600,
    green: colors.green.c600,
    gray: colors.gray.c400,
  },
  hover: {
    sky: colors.sky.c700,
    blue: colors.blue.c700,
    indigo: colors.indigo.c700,
    red: colors.red.c700,
    pink: colors.pink.c700,
    orange: colors.orange.c500,
    yellow: colors.yellow.c500,
    lime: colors.lime.c700,
    green: colors.green.c700,
    gray: colors.gray.c500,
  },
}
