export const COLORS = {
  BOARD: {
    BG: {
      sky: 'bg-sky-700',
      blue: 'bg-blue-700',
      indigo: 'bg-indigo-700',
      red: 'bg-red-700',
      pink: 'bg-pink-700',
      orange: 'bg-orange-500',
      yellow: 'bg-yellow-500',
      lime: 'bg-lime-700',
      green: 'bg-green-700',
      gray: 'bg-gray-500',
      black: 'bg-black-90',
    },
    INPUT_FOCUS: {
      sky: 'focus:border-sky-600',
      blue: 'focus:border-blue-600',
      indigo: 'focus:border-indigo-600',
      red: 'focus:border-red-600',
      pink: 'focus:border-pink-600',
      orange: 'focus:border-orange-400',
      yellow: 'focus:border-yellow-400',
      lime: 'focus:border-lime-600',
      green: 'focus:border-green-600',
      gray: 'focus:border-gray-400',
      black: 'focus:border-black-80',
    },
    BTN: {
      sky: 'bg-sky-600',
      blue: 'bg-blue-600',
      indigo: 'bg-indigo-600',
      red: 'bg-red-600',
      pink: 'bg-pink-600',
      orange: 'bg-orange-400',
      yellow: 'bg-yellow-400',
      lime: 'bg-lime-600',
      green: 'bg-green-600',
      gray: 'bg-gray-400',
      black: 'bg-black-80',
    },
    BTN_HOVER: {
      sky: 'hover:bg-sky-700',
      blue: 'hover:bg-blue-700',
      indigo: 'hover:bg-indigo-700',
      red: 'hover:bg-red-700',
      pink: 'hover:bg-pink-700',
      orange: 'hover:bg-orange-500',
      yellow: 'hover:bg-yellow-500',
      lime: 'hover:bg-lime-700',
      green: 'hover:bg-green-700',
      gray: 'hover:bg-gray-500',
      black: 'hover:bg-black-90',
    },
  },
}
