services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  TagService\Api\Controller\:
    resource: '%kernel.project_dir%/src/Api/Controller/'

  TagService\Api\Infrastructure\Event\ErrorSubscriber:
    tags:
      - 'kernel.event_subscriber'